# Use case configuration for Samsung Galaxy Tab S6 Lite (2022) (gta4xlve)

SectionVerb {
	EnableSequence [
		# Two TAS2562 on quinary MI2S, fed from MultiMedia1
		cset "name='QUIN_MI2S_RX Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='QUIN_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker playback"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0" # MultiMedia1
		PlaybackChannels 2
	}
}
